channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- aiohttp=3.7.4.post0
- aiohttp-cors=0.7.0
- aiosignal=1.3.1
- alembic=1.8.1
- ansicon=1.89.0
- anyio=3.6.2
- appdirs=1.4.4
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- asn1crypto=1.5.1
- asttokens=2.2.1
- async-timeout=3.0.1
- attrs=22.2.0
- backcall=0.2.0
- backports=1.0
- backports.functools_lru_cache=1.6.4
- beautifulsoup4=4.12.2
- blas=2.116
- blas-devel=3.9.0
- bleach=6.0.0
- blessed=1.19.1
- blinker=1.4
- brotli=1.0.9
- brotli-bin=1.0.9
- brotlipy=0.7.0
- bzip2=1.0.8
- c-ares=1.18.1
- ca-certificates=2023.7.22
- cachetools=5.3.0
- certifi=2023.7.22
- cffi=1.15.1
- chardet=4.0.0
- charset-normalizer=3.1.0
- click=8.1.3
- cloudpickle=2.0.0
- colorama=0.4.6
- colorful=0.5.4
- comm=0.1.3
- configparser=5.0.2
- contourpy=1.0.7
- cryptography=40.0.2
- cuda-cccl=12.1.109
- cuda-cudart=11.8.89
- cuda-cudart-dev=11.8.89
- cuda-cupti=11.8.87
- cuda-libraries=11.8.0
- cuda-libraries-dev=11.8.0
- cuda-nvrtc=11.8.89
- cuda-nvrtc-dev=11.8.89
- cuda-nvtx=11.8.86
- cuda-profiler-api=12.1.105
- cuda-runtime=11.8.0
- cycler=0.11.0
- cython=3.0.3
- daal4py=2023.1.1
- dal=2023.1.1
- databricks-cli=0.17.6
- debugpy=1.6.7
- decorator=5.1.1
- defusedxml=0.7.1
- dill=0.3.6
- distlib=0.3.6
- dnspython=2.3.0
- docker-py=4.4.1
- docker-pycreds=0.4.0
- dynaconf=3.1.12
- dython=0.7.3
- entrypoints=0.4
- et_xmlfile=1.1.0
- executing=1.2.0
- filelock=3.12.0
- flask=2.2.2
- flit-core=3.8.0
- fonttools=4.39.3
- freetype=2.12.1
- frozenlist=1.3.3
- gettext=0.21.1
- gitdb=4.0.7
- gitpython=3.1.30
- glib=2.76.2
- glib-tools=2.76.2
- google-api-core=2.10.1
- google-auth=2.17.3
- googleapis-common-protos=1.57.0
- gpustat=1.0.0
- greenlet=2.0.1
- grpc-cpp=1.48.1
- gst-plugins-base=1.22.0
- gstreamer=1.22.0
- hdbscan=0.8.33
- icu=72.1
- idna=3.4
- imbalanced-learn=0.10.1
- importlib-metadata=6.6.0
- importlib_metadata=6.6.0
- importlib_resources=5.12.0
- intel-openmp=2023.1.0
- ipykernel=6.22.0
- ipython=8.12.0
- ipython_genutils=0.2.0
- itsdangerous=2.0.1
- jedi=0.18.2
- jinja2=3.1.2
- jinxed=1.2.0
- joblib=1.2.0
- jsonschema=4.17.3
- jupyter_client=8.2.0
- jupyter_core=5.3.0
- jupyter_events=0.6.3
- jupyter_server=2.5.0
- jupyter_server_terminals=0.4.4
- jupyterlab_pygments=0.2.2
- kiwisolver=1.4.4
- krb5=1.20.1
- lcms2=2.15
- lerc=4.0.0
- libabseil=20220623.0
- libblas=3.9.0
- libbrotlicommon=1.0.9
- libbrotlidec=1.0.9
- libbrotlienc=1.0.9
- libcblas=3.9.0
- libclang13=16.0.2
- libcublas=11.11.3.6
- libcublas-dev=11.11.3.6
- libcufft=10.9.0.58
- libcufft-dev=10.9.0.58
- libcurand=10.3.2.106
- libcurand-dev=10.3.2.106
- libcusolver=11.4.1.48
- libcusolver-dev=11.4.1.48
- libcusparse=11.7.5.86
- libcusparse-dev=11.7.5.86
- libdeflate=1.18
- libffi=3.4.2
- libglib=2.76.2
- libhwloc=2.9.1
- libiconv=1.17
- libjpeg-turbo=2.1.5.1
- liblapack=3.9.0
- liblapacke=3.9.0
- libnpp=11.8.0.86
- libnpp-dev=11.8.0.86
- libnvjpeg=11.9.0.86
- libnvjpeg-dev=11.9.0.86
- libogg=1.3.4
- libpng=1.6.39
- libprotobuf=3.20.1
- libsodium=1.0.18
- libsqlite=3.40.0
- libtiff=4.5.0
- libuv=1.44.2
- libvorbis=1.3.7
- libwebp-base=1.3.0
- libxcb=1.13
- libxml2=2.10.4
- libzlib=1.2.13
- lightgbm=3.3.5
- llvmlite=0.40.1
- loguru=0.7.0
- m2w64-gcc-libgfortran=5.3.0
- m2w64-gcc-libs=5.3.0
- m2w64-gcc-libs-core=5.3.0
- m2w64-gmp=6.1.0
- m2w64-libwinpthread-git=5.0.0.4634.697f757
- mako=1.2.3
- markupsafe=2.1.2
- matplotlib=3.7.1
- matplotlib-base=3.7.1
- matplotlib-inline=0.1.6
- missingno=0.4.2
- mistune=2.0.5
- mkl=2022.1.0
- mkl-devel=2022.1.0
- mkl-include=2022.1.0
- mlflow=1.26.1
- mpmath=1.3.0
- msgpack-python=1.0.5
- msys2-conda-epoch=20160418
- multidict=6.0.4
- multiprocess=0.70.14
- munkres=1.1.4
- nb_conda_kernels=2.3.1
- nbclassic=0.5.5
- nbclient=0.7.4
- nbconvert=7.3.1
- nbconvert-core=7.3.1
- nbconvert-pandoc=7.3.1
- nbformat=5.8.0
- nest-asyncio=1.5.6
- networkx=3.1
- nodejs=18.15.0
- notebook=6.5.4
- notebook-shim=0.2.3
- numba=0.57.1
- numpy=1.24.3
- nvidia-ml-py=11.495.46
- oauthlib=3.2.2
- opencensus=0.11.2
- opencensus-context=0.1.3
- openjpeg=2.5.0
- openpyxl=3.0.10
- openssl=3.1.3
- packaging=23.1
- pandas=2.0.1
- pandoc=2.19.2
- pandocfilters=1.5.0
- parso=0.8.3
- pcre2=10.40
- pickleshare=0.7.5
- pillow=9.5.0
- pip=23.1.2
- pkgutil-resolve-name=1.3.10
- platformdirs=3.4.0
- ply=3.11
- pooch=1.7.0
- pot=0.9.0
- prometheus_client=0.16.0
- prometheus_flask_exporter=0.22.3
- prompt-toolkit=3.0.38
- prompt_toolkit=3.0.38
- psutil=5.9.5
- pthread-stubs=0.4
- pthreads-win32=2.9.1
- pure_eval=0.2.2
- py-spy=0.3.14
- pyaml=21.10.1
- pyasn1=0.4.8
- pyasn1-modules=0.2.7
- pycparser=2.21
- pydantic=1.10.7
- pygments=2.15.1
- pyjwt=2.4.0
- pymongo=4.3.3
- pynndescent=0.5.10
- pyopenssl=23.1.1
- pyparsing=3.0.9
- pyqt=5.15.7
- pyqt5-sip=12.11.0
- pyrsistent=0.19.3
- pysocks=1.7.1
- python=3.10.10
- python-dateutil=2.8.2
- python-fastjsonschema=2.16.3
- python-json-logger=2.0.7
- python-tzdata=2023.3
- python_abi=3.10
- pytorch=2.0.0
- pytorch-cuda=11.8
- pytorch-mutex=1.0
- pytz=2023.3
- pyu2f=0.1.5
- pywin32=304
- pywinpty=2.0.10
- pyyaml=6.0
- pyzmq=25.0.2
- qt-main=5.15.8
- querystring_parser=1.2.4
- ray-core=2.3.0
- ray-dashboard=2.3.0
- ray-default=2.3.0
- ray-tune=2.3.0
- re2=2022.06.01
- requests=2.29.0
- rfc3339-validator=0.1.4
- rfc3986-validator=0.1.1
- rsa=4.9
- scikit-learn=1.2.2
- scikit-learn-intelex=2023.1.1
- scikit-optimize=0.9.0
- scikit-plot=0.3.7
- scipy=1.10.1
- seaborn=0.12.2
- send2trash=1.8.0
- setproctitle=1.2.2
- setuptools=67.7.2
- sip=6.7.9
- six=1.16.0
- smart_open=6.3.0
- smmap=4.0.0
- sniffio=1.3.0
- soupsieve=2.3.2.post1
- sqlalchemy=1.4.39
- sqlparse=0.4.3
- stack_data=0.6.2
- sympy=1.11.1
- tabulate=0.9.0
- tensorboardx=2.5.1
- terminado=0.17.0
- threadpoolctl=3.1.0
- tinycss2=1.2.1
- tk=8.6.12
- toml=0.10.2
- tomli=2.0.1
- tornado=6.3
- tqdm=4.65.0
- traitlets=5.9.0
- tune-sklearn=0.4.1
- typing-extensions=4.5.0
- typing_extensions=4.5.0
- tzdata=2023c
- ucrt=10.0.22621.0
- umap-learn=0.5.4
- unicodedata2=15.0.0
- urllib3=1.26.15
- vc=14.3
- vc14_runtime=14.34.31931
- virtualenv=20.22.0
- vs2015_runtime=14.34.31931
- waitress=2.0.0
- wcwidth=0.2.6
- webencodings=0.5.1
- websocket-client=1.5.1
- werkzeug=2.2.3
- wheel=0.40.0
- win32_setctime=1.1.0
- win_inet_pton=1.1.0
- winpty=0.4.3
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xz=5.2.6
- yaml=0.2.5
- yarl=1.9.1
- zeromq=4.3.4
- zipp=3.15.0
- zlib=1.2.13
- zstd=1.5.2
- pip:
  - absl-py==2.0.0
  - antlr4-python3-runtime==4.9.3
  - astunparse==1.6.3
  - data==0.4
  - dm-tree==0.1.8
  - flatbuffers==23.5.26
  - funcsigs==1.0.2
  - future==0.18.3
  - gast==0.5.4
  - google-auth-oauthlib==1.0.0
  - google-pasta==0.2.0
  - gower==0.1.2
  - grpcio==1.59.0
  - h5py==3.9.0
  - hydra-core==1.3.2
  - keras==2.14.0
  - latex==0.7.0
  - libclang==16.0.6
  - markdown==3.5
  - ml-dtypes==0.2.0
  - omegaconf==2.3.0
  - opt-einsum==3.3.0
  - protobuf==4.24.4
  - pyampute==0.0.3
  - requests-oauthlib==1.3.1
  - scienceplots==2.1.0
  - sciplot==0.8.1
  - shutilwhich==1.1.0
  - tbb==2021.9.0
  - tempdir==0.7.1
  - tensorboard==2.14.1
  - tensorboard-data-server==0.7.1
  - tensorflow-estimator==2.14.0
  - tensorflow-intel==2.14.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - tensorflow-probability==0.22.0
  - termcolor==2.3.0
  - torchaudio==2.0.0
  - torchvision==0.15.0
  - wrapt==1.14.1
name: fed_imp
