channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- dynaconf=3.2.0
- dython=0.7.4
- imbalanced-learn=0.11.0
- lightgbm=4.0.0
- missingno=0.4.2
- pip=23.2.1
- pip:
  - antlr4-python3-runtime==4.9.3
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - pyampute==0.0.3
  - tbb==2021.9.0
  - torchaudio==2.0.0
  - torchvision==0.15.0
name: fed_imp
