channels:
- pytorch
- pyviz
- bokeh
- nvidia
- conda-forge
- defaults
dependencies:
- conda=23.3.1
- conda-libmamba-solver=23.1.0
- console_shortcut=0.1.1
- cvxpy=1.3.0
- dynaconf=3.1.11
- dython=0.7.4
- future=0.18.2
- hyperopt=0.2.7
- ipykernel=6.23.3
- ipympl=0.9.3
- jupyter=1.0.0
- jupyter_bokeh=3.0.5
- jupyter_contrib_nbextensions=0.7.0
- jupyter_nbextensions_configurator=0.6.1
- lightgbm=3.3.5
- loguru=0.6.0
- mamba=1.2.0
- matplotlib=3.6.3
- menuinst=1.4.19
- missingno=0.4.2
- mmh3=3.0.0
- openpyxl=3.1.1
- optuna=3.1.0
- pandas=2.0.0
- panel=0.14.4
- pot=0.9.0
- powershell_shortcut=0.0.1
- py-xgboost-cpu=1.7.1
- pycryptodome=3.16.0
- pylint=2.16.1
- pymongo=4.3.3
- pytest=7.2.1
- pytorch=1.13.1
- scikit-learn=1.2.1
- scikit-optimize=0.9.0
- scipy=1.10.0
- pip:
  - absl-py==1.4.0
  - aiohttp==3.8.3
  - aiohttp-cors==0.7.0
  - aiosignal==1.3.1
  - ansicon==1.89.0
  - antlr4-python3-runtime==4.9.3
  - arrow==1.2.3
  - arviz==0.15.1
  - astunparse==1.6.3
  - async-timeout==4.0.2
  - autoimpute==0.13.0
  - blessed==1.19.1
  - cachetools==5.3.0
  - click==8.1.3
  - colorful==0.5.5
  - cons==0.4.5
  - distlib==0.3.6
  - dm-tree==0.1.8
  - etils==1.1.1
  - etuples==0.3.8
  - fastprogress==1.0.3
  - filelock==3.9.0
  - flatbuffers==23.1.21
  - flwr==1.3.0
  - fqdn==1.5.1
  - frozenlist==1.3.3
  - gast==0.4.0
  - google-api-core==2.11.0
  - google-auth==2.16.0
  - google-auth-oauthlib==0.4.6
  - google-pasta==0.2.0
  - googleapis-common-protos==1.58.0
  - gpustat==1.0.0
  - grpcio==1.51.1
  - h5netcdf==1.1.0
  - h5py==3.8.0
  - hydra-core==1.3.2
  - imbalanced-learn==0.10.1
  - isoduration==20.11.0
  - iterators==0.0.2
  - jinxed==1.2.0
  - jsonpointer==2.3
  - jupyter-contrib-core==0.4.2
  - jupyter-nbextensions-configurator==0.6.1
  - keras==2.11.0
  - libclang==15.0.6.1
  - logical-unification==0.4.5
  - markdown==3.4.1
  - minikanren==1.0.3
  - msgpack==1.0.4
  - multidict==6.0.4
  - multipledispatch==0.6.0
  - nvidia-ml-py==11.495.46
  - oauthlib==3.2.2
  - omegaconf==2.3.0
  - opencensus==0.11.1
  - opencensus-context==0.1.3
  - opt-einsum==3.3.0
  - platformdirs==2.6.2
  - prometheus-client==0.13.1
  - promise==2.3
  - protobuf==3.19.6
  - py-spy==0.3.14
  - pyampute==0.0.3
  - pyasn1==0.4.8
  - pyasn1-modules==0.2.8
  - pydantic==1.10.4
  - pymc==5.1.0
  - pytensor==2.10.1
  - ray==2.2.0
  - requests-oauthlib==1.3.1
  - rsa==4.9
  - scienceplots==2.0.1
  - smart-open==6.3.0
  - sqlalchemy==1.3.23
  - tabulate==0.9.0
  - tensorboard==2.11.2
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.1
  - tensorboardx==2.6
  - tensorflow==2.11.0
  - tensorflow-datasets==4.8.3
  - tensorflow-estimator==2.11.0
  - tensorflow-intel==2.11.0
  - tensorflow-io-gcs-filesystem==0.31.0
  - tensorflow-metadata==1.12.0
  - tensorflow-probability==0.19.0
  - termcolor==2.2.0
  - torchaudio==0.13.1
  - torchvision==0.14.1
  - tune-sklearn==0.4.5
  - uri-template==1.2.0
  - virtualenv==20.17.1
  - webcolors==1.12
  - werkzeug==2.2.3
  - xarray==2023.1.0
  - xarray-einstats==0.5.1
  - xgboost==1.7.4
  - yarl==1.8.2
name: base
