channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- joblib=1.2.0
- jupyter=1.0.0
- loguru=0.7.0
- matplotlib=3.7.1
- nb_conda_kernels=2.3.1
- notebook=6.5.4
- pandas=2.0.1
- pot=0.9.0
- pymongo=4.3.3
- pytorch=2.0.0
- scikit-learn=1.2.2
- tqdm=4.65.0con
- tune-sklearn=0.4.1
- pip:
  - antlr4-python3-runtime==4.9.3
  - hydra-core==1.3.2
  - omegaconf==2.3.0
  - pyampute==0.0.3
  - tbb==2021.9.0
  - torchaudio==2.0.0
  - torchvision==0.15.0
name: fed_imp
