# @package config_tmpl

# num_clients
num_clients: 10

# dataset
data:
  dataset_name: breast
  normalize: true

# dataset partition
data_partition:
  strategy: full
  params: {}

handle_imbalance: null

# missing data simulation
missing_simulate:
  mf_strategy: all
  mm_strategy: s3
  mm_strategy_params:
    corr_type: others

# imputation method
imputation:
  initial_strategy: mean
  clip: true
  imp_model_params:
    latent_size: 32
    n_hidden: 64
    K: 10
    L: 1000
  imp_params:
    lr: 1e-3
    batch_size: 256
    weight_decay: 0.0001
    optimizer: adam

# aggregation strategy
agg_strategy_imp:
  strategy: local
  params:
    ms_field: missing_cell_pct
    beta: 0.7

# server
client_type: vae
server_type: vae
server:
  imp_round: 100            # global epoch
  imp_local_epochs: 5       # local epoch
  pred_round: 0
  pred_local_epochs: 0
  verbose: 5

# prediction model
pred_model:
  model_params:
    model: 2nn
    num_hiddens: 32
    model_init_config: null
    model_other_params: null
  train_params:
    batch_size: 128
    learning_rate: 0.001
    weight_decay: 0.0001
    pred_round: 200
    pred_local_epochs: 3


# fed_imp
experiment:
  n_rounds: 5
  seed: 102931466 # 102931466
  mtp: true
  random_seed: 50 # 50
  num_process: 5
  test_size: 0.1

track: false
tune_params: false
prediction: false
save_state: true

# params
algo_params:
  central: {}
  central2: {}
  central_vae: { }   # todo: rename this to central_nn
  central_gain: { }   # todo: rename this to central_nn
  local: { }
  local_vae: { }
  local_gain: { }
  fedavg: { }
  fedavg_vae: { }    # todo: rename this to fedavg_nn
  fedavg_gain: { }    # todo: rename this to fedavg_nn
  fedwavg:
    alpha: 0.9
  fedmechw:
    client_thres: 1.0
    alpha: 1.0
    beta: 0.0,
    scale_factor: 4
  fedmechw_p:
    client_thres: 1.0
    alpha: 0.85
    beta: 0.1
    scale_factor: 4
  fedmechw_new:
    client_thres: 1.0
    alpha: 0.95
    gamma: 0.02
    scale_factor: 4
  fedmechw_p_sigmoid:
    client_thres: 1.0
    alpha: 0.9
    beta: 0.1
    scale_factor: 3
  fedmechclw:
    client_thres: 1.0
    thres1: 0.2
    alpha: 0.8
  scale_factor: 6