experiment_name: fed_imp_pc2
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp4
  - config_vars/imp4:
      - cardio_exp1
      - cardio_exp2
  - _self_