experiment_name: fed_imp9
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp4
  - config_vars/imp_pc1:
      - codrna_exp3
      - codon_exp3
      - skin_exp3
      - heart_exp3
  - _self_