experiment_name: fed_imp_pc2
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp4
  - config_vars/imp4:
      - codrna_exp1
      - codrna_exp2
      - codon_exp1
      - codon_exp2
  - _self_