experiment_name: fed_imp_pc3
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp_gain
  - config_vars/imp_extention:
      - ext_exp3
      - ext_exp31
  - _self_