experiment_name: fed_imp_ext2_pc2
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp_new
  - config_vars/imp_extention2:
      - vehicle_exp
  - _self_
