experiment_name: fed_imp9
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp4
  - config_vars/imp_pc1:
      - skin_exp1
      - skin_exp2
      - heart_exp1
      - heart_exp2
  - _self_