experiment_name: fed_imp
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp_config_tmplate
  - config_vars:
      - exp_demo
      - exp_demo_gain
      - exp_demo_miwae
  - _self_