experiment_name: fed_imp_ext2_amarel
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp_vae
  - config_vars/imp_extention2:
      - ext_exp21
  - _self_