experiment_name: fed_imp_pc2
debug: false
experiment_marker:
  - num_clients
  - server@imp_round
defaults:
  - config_tmpl: imp_pc2
  - config_vars/imp_pc2:
      - codon_exp1
      - codon_exp2
  - _self_